import Image from 'next/image'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import LoginCard from './Components/LoginCard'
import logo from '../public/images/nit-logo15954991401255.jpg'
import TopCards from './Components/TopCards'
import Response from './Components/Response'
import StudentDetails from './Components/StudentDetails'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
   <>
    <Head>
        <title>NITH | MMCA</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <main className='bg-gray-100 min-h-screen'>
        {/* <Header /> */}
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <Response/>
          <StudentDetails/>
        </div>
      </main>
   </>
  )
}
